# Stage 1: Build GraalVM Native Executable
FROM quay.io/quarkus/ubi-quarkus-mandrel-builder-image:23.1-java21 AS build

USER root
WORKDIR /code

COPY pom.xml ./
COPY src ./src

# Build native binary executable using preinstalled Maven
RUN mvn package -Dnative -DskipTests -B

# Stage 2: Ultra-lightweight Native Runtime
FROM quay.io/quarkus/quarkus-micro-image:2.0

WORKDIR /work/

COPY --from=build --chown=1001:root /code/target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
