# Default values for portfolio-chart

global:
  domain: "portfolio.example.com"
  staticIpName: "portfolio-ip"

frontend:
  replicaCount: 1
  image:
    repository: "europe-north1-docker.pkg.dev/portfolio-503914/portfolio/portfolio-frontend"
    tag: "latest"
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  pdb:
    enabled: true
    maxUnavailable: 1

backend:
  replicaCount: 1
  image:
    repository: "europe-north1-docker.pkg.dev/portfolio-503914/portfolio/portfolio-backend"
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  env:
    quarkusCorsOrigins: "https://portfolio.example.com"
  pdb:
    enabled: true
    maxUnavailable: 1

serviceAccount:
  create: true
  name: "portfolio-sa"
  annotations: {}

ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "portfolio-managed-cert"
  staticIpName: "portfolio-ip"

ssl:
  managedCertificate:
    enabled: true
    name: "portfolio-managed-cert"
    domains:
      - "portfolio.example.com"
