{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
    {{- if .Values.ingress.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.ingress.staticIpName }}"
    {{- end }}
    {{- if .Values.ssl.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: "{{ .Values.ssl.managedCertificate.name }}"
    {{- end }}
spec:
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
